# Generated by Django 3.2.25 on 2024-08-06 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_polly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parrot',
            name='tricks',
        ),
        migrations.AddField(
            model_name='parrot',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Trick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('parrot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tricks', to='django_polly.parrot')),
            ],
        ),
    ]
