# Generated by Django 3.2.25 on 2024-08-09 00:58

from django.db import migrations, models
import django_polly.lib.llm_api


class Migration(migrations.Migration):

    dependencies = [
        ('django_polly', '0002_auto_20240806_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='parrot',
            name='model',
            field=models.CharField(choices=[('mistral-7b-instruct-v0.1.Q4_0.gguf', 'MISTRAL_0_1_INSTRUCT'), ('Meta-Llama-3-8B-Instruct.Q8_0.gguf', 'META_LLAMA_3_INSTRUCT'), ('Meta-Llama-3.1-8B-Instruct.Q4_0.gguf', 'META_LLAMA_3_1_INSTRUCT'), ('Phi-3-mini-4k-instruct.Q4_0.gguf', 'PHI_3_MINI_INSTRUCT'), ('Qwen2-500M-Instruct-Q8_0.gguf', 'QWEN2_INSTRUCT'), ('llama-pro-8b.Q8_0.gguf', 'LLAMA_PRO')], default=django_polly.lib.llm_api.LLMModelType['QWEN2_INSTRUCT'], max_length=255),
        ),
    ]
